### ISSUE TITLE
Why not use query string parameters?

### ISSUE THREAD

**Issue by sharbel-clearfood** [sbt/sbt-digest#16]
Just curious as to why we cannot use querystring instead of adding the checksum to the filename. That ways we do not have to change the files themselves.

Earlier (6-8 years back) it was recommended not to use query string for caching as there were some proxy servers that did not cache urls with query string. But that doesn't look like the case now and most people are resorting to query strings. Grunt cache bust plugin also only changes only query string by default.

Is it because it is difficult to support require (since you specify files without the js extension due to which it is difficult to add a url parameter) that you went down with this approach?

Thanks,
Sharbel Cherian

**Comment by ethereal-sandeep** [comment]
The query string strategy has several disadvantages:

1. Not all caches will reliably cache content where the filename only differs by query parameters

- Steve Souders recommends, "...avoiding a querystring for cacheable resources". He found that in this case 5-20% of requests will not be cached. Query strings in particular do not work at all with some CDNs for cache invalidation.

2. The file name can change between nodes in multi-server environments.

- The default query string in Rails 2.x is based on the modification time of the files. When assets are deployed to a cluster, there is no guarantee that the timestamps will be the same, resulting in different values being used depending on which server handles the request.

3. Too much cache invalidation

- When static assets are deployed with each new release of code, the mtime (time of last modification) of all these files changes, forcing all remote clients to fetch them again, even when the content of those assets has not changed.

c.f http://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark

**Comment by jroper** [comment]
Play's/sbt-web's asset versioning is not based on using a timestamp but based on file contents so most of the points above are irrelevant.

The reason for putting it in the filename is because the two files are actually different. They are not just different versions of the same asset, they are completely different assets. You can't substitute in one version for another, if you deploy a new version of the site, but a client has an old version of the page that is requesting an old version of the asset, you don't want the server to give it the new version of the asset because the page will potentially not work with that new version. By changing the filename, you allow both versions to coexist, both the new version and the old version can be simultaneously deployed, and so outdated cached assets that refer to outdated other assets don't get broken every time you deploy.
